Brightness parameters pass from TI's AEWB function
autobrains/edgeai-tiovx-apps pull request #10
Opened 2024-09-03 11:45 UTC by YardenLeaf

This PR is  required to later implement CNN switch based on brightness parameters taken from the ISP.

2024-09-04 14:01 UTC, TomerSegalAB requested changes

2024-09-04 14:01 UTC, TomerSegalAB commented on aewb_logger/aewb_logger_sender.c
instead of this:

```
image_sensor_processor_run()
    aewb_process(handle, 2a_buf, wb_buf)  
        aewb_logger_send_log(handle , 2a_buf, wb_buf, frame_brightness_params) //new arg
            //build buf, send udp
            frame_brightness_params = handle... //new code
    
        return yarden_state //new retval
```
i think it should look like this:
```
image_sensor_processor_run()
    aewb_process(handle, 2a_buf, wb_buf)  //unchanged
    
    get_frame_brightness_params(AewbHandle *handle, frame_brightness_params_t frame_brightness_params)
        frame_brightness_params->avg_brightness = handle->ti_2a_wrapper->p_ae_params->avg_y;
    	frame_brightness_params->exposure_time  = handle->ti_2a_wrapper->p_ae_params->prev_ae.exposure_time;
	frame_brightness_params->analog_gain    = handle->ti_2a_wrapper->p_ae_params->prev_ae.analog_gain;
	frame_brightness_params->digital_gain   = handle->ti_2a_wrapper->p_ae_params->prev_ae.digital_gain;
```    
`get_frame_brightness_params()` can be implemented in `aewb_logger_sender.c` or in `image_sensor_processor.c`.
i think `image_sensor_processor.c` already includes all the relevant data types.

2024-09-04 14:01 UTC, TomerSegalAB commented on aewb_logger/aewb_logger_sender.c
`avg_y` - this is the sum of avg brightness of the last 10 frames.
i would use `history_brightness` instead, which holds the individual avg brightness of the last 10 frames.

2024-09-04 14:01 UTC, TomerSegalAB commented on modules/core/include/tiovx_modules_types.h
>  /*!
analog_gain; // 1024 = x1 gain, 2048 = x2 gain...
digital_gain; // 256 = x1 gain,  512 = x2 gain...
exposure_time; // msec
avg_brightness; // 0 = last 10 frames were black = 0% brightness, 2550 = last 10 frames were white = 100% brightness

2024-09-09 12:36 UTC, EvyatarTamirAB approved these changes

2024-09-09 12:55 UTC, TomerSegalAB approved these changes

2024-09-09 13:07 UTC, merged