move imx728 exposure/gain params to yaml file, remove aewb_logger typ…
autobrains/edgeai-tiovx-apps pull request #9
Opened 2024-07-07 13:40 UTC by TomerSegalAB

* added loading of AE params (min/max exposure, min/max gain, target brightness...) from yaml.
   * `ae_params_get()` will try to find the yaml in these paths (in order of precedence):
   * env var  `AE_PARAMS_PATH`
   * `./ae_params.yaml` (current working dir)
   * `/home/root/app/imx728/dcc_3856x2176/ae_params.yaml`
        *  most users will be loading form this path which is a part of the official release.
* changed the aewb_logger api from using `edgeai-tiovx-apps` specific types (like `AewbHandle`) to using `ti_2a_wrapper.h` types (to match both `edgeai-tiovx-apps` and `edgeai-gst-plugins`).
* added `aewb_debug_utils` file for code we use for debug sessions (should be in git), but is never part of the official, but isn't part of the official version.
* moved `_AewbHandle` back into `linux_aewb_module.c` (i previously moved it when aewb_logger was tightly bound to `edgeai-tiovx-apps` types) 

@YardenLeaf please ignore Renesas style rules, we'll deal with it if/when we ever merge into Renesas

2024-07-08 10:28 UTC, YardenLeaf requested changes

2024-07-08 10:28 UTC, YardenLeaf commented on modules/src/linux_aewb_module.c
> +#define AE_PARAMS_FROM_FILE 1
move to CMAKE flag

2024-07-08 15:59 UTC, TomerSegalAB commented on modules/src/linux_aewb_module.c
> +#define AE_PARAMS_FROM_FILE 1
fixed.

2024-07-10 13:19 UTC, YardenLeaf approved these changes

2024-07-10 13:19 UTC, merged